#!/usr/bin/env 
bash
/usr/lib/jvm/jdk-8.181-i586/bin/java 
-DMono=/usr/bin/mono-sgen 
-DMono4.0_x64=/usr/lib/mono/4.0 
-DMono4.5_x64=/usr/lib/mono/4.5 
-DMonoVersion=5.16.0.179 
-Dagent.home.dir=/opt/buildAgent 
-Dagent.name=teamcity-linux-4275 
-Dagent.ownPort=9090 
-Dagent.persistent.cache=/opt/buildAgent/system/.persistent_cache 
-Dagent.work.dir=/opt/buildAgent/work 
-Dant.home=/opt/buildAgent/plugins/ant 
-Dbuild.number=4403 
-Dbuild.vcs.number.TC_TeamCityCore=f26423c8d3ab6e1f7b1fe949296a921a62b0b8bf 
-Dbuild.vcs.number.TeamCity_Subversion=94865 
-Dgant.home=/opt/buildAgent/tools/gant 
-Dgroovy.home=/opt/buildAgent/tools/gant 
-Dgroovy.starter.conf=/opt/buildAgent/tools/gant/conf/gant-starter.conf 
-Didea.home.path=/opt/buildAgent/tools/idea 
-Djava.awt.headless=true 
-Djava.io.tmpdir=/opt/buildAgent/temp/buildTmp 
-Djetbrains.sign.jet-sign.version=42.28 
-Djetbrains.sign.teamcity.disable=true 
-Djna.nosys=true 
-Djps.bundled.ant.path=/opt/buildAgent/plugins/ant 
-Djps.fallback.jdk.home=/usr/lib/jvm/jdk-8.181-i586 
-Djps.fallback.jdk.version=1.8 
-Dpath.macro.USER.HOME= 
-Dpin.builds.user.name=builduser 
-Dpin.builds.user.password=******* 
-Dscript.name=/opt/buildAgent/temp/buildTmp/jps.gant 
-Dteamcity.agent.cpuBenchmark=619 
-Dteamcity.agent.dotnet.agent_url=http://localhost:9090/RPC2 
-Dteamcity.agent.dotnet.build_id=38445064 
-Dteamcity.agent.ensure.free.space=15gb 
-Dteamcity.agent.hardware.cpuCount=1 
-Dteamcity.agent.hardware.memorySize=3945 
-Dteamcity.auth.password=******* 
-Dteamcity.auth.userId=TeamCityBuildId=38445064 
-Dteamcity.build.changedFiles.file=/opt/buildAgent/temp/buildTmp/changedFiles7581062972113556392.txt 
-Dteamcity.build.checkoutDir=/opt/buildAgent/work/b775fede4ed4637f 
-Dteamcity.build.id=38445064 
-Dteamcity.build.properties.file=/opt/buildAgent/temp/buildTmp/teamcity.build8496090477597959349.properties 
-Dteamcity.build.tempDir=/opt/buildAgent/temp/buildTmp 
-Dteamcity.build.workingDir=/opt/buildAgent/work/b775fede4ed4637f 
"-Dteamcity.buildConfName=DSL 
UI 
Tests" 
-Dteamcity.buildType.id=TC_Trunk_IntegrationTests_DslUiTests 
-Dteamcity.configuration.properties.file=/opt/buildAgent/temp/buildTmp/teamcity.config9579567260607516922.properties 
-Dteamcity.ipr.settings.file=/opt/buildAgent/temp/buildTmp/idearunner17142016295392558859xml 
-Dteamcity.nuget.feed._Root.default.publicUrl=https://buildserver.labs.intellij.net/httpAuth/app/nuget/feed/_Root/default/ 
-Dteamcity.nuget.feed._Root.default.url=https://buildserver.labs.intellij.net/httpAuth/app/nuget/feed/_Root/default/ 
"-Dteamcity.projectName=Integration 
Tests" 
-Dteamcity.runner.properties.file=/opt/buildAgent/temp/buildTmp/teamcity.runner13336387702326568032.properties 
-Dteamcity.runtime.props.file=/opt/buildAgent/temp/agentTmp/ant11129201135403792197runtime 
-Dteamcity.tests.recentlyFailedTests.file=/opt/buildAgent/temp/buildTmp/testsToRunFirst3848569069744282146.txt 
-Dteamcity.tests.runRiskGroupTestsFirst=recentlyFailed,newAndModified,affectedTestsDependencyBased 
"-Dteamcity.version=2018.2 
EAP3 
(build 
60770)" 
-Duse.memory.temp.cache=true 
-Duser.language=en 
-Xmx512m 
-XX:MaxPermSize=400m 
-classpath 
/opt/buildAgent/tools/gant/bootstrap/javac-aware-groovy-starter.jar 
jetbrains.buildServer.agent.ideaRunner.ToolsAwareGroovyStarter 
/opt/buildAgent/tools/gant/lib/groovy-all-2.4.11.jar 
org.codehaus.groovy.tools.GroovyStarter 
--main 
gant.Gant 
--conf 
/opt/buildAgent/tools/gant/conf/gant-starter.conf 
--classpath 
. 
-f 
/opt/buildAgent/temp/buildTmp/jps.gant 
-P 
/opt/buildAgent/tools/jps/lib/slf4j-api-1.7.10.jar:/opt/buildAgent/tools/jps/lib/nanoxml-2.2.3.jar:/opt/buildAgent/tools/jps/lib/slf4j-log4j12-1.7.10.jar:/opt/buildAgent/tools/jps/lib/jna.jar:/opt/buildAgent/tools/jps/lib/jdom.jar:/opt/buildAgent/tools/jps/lib/snappy-in-java-0.5.1.jar:/opt/buildAgent/tools/jps/lib/jpa-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/org.osgi.namespace.extender-1.0.1.jar:/opt/buildAgent/tools/jps/lib/idea_rt.jar:/opt/buildAgent/tools/jps/lib/netty-all-4.1.13.Final.jar:/opt/buildAgent/tools/jps/lib/eclipse-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/jps-common.jar:/opt/buildAgent/tools/jps/lib/groovy-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/aspectj-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/jps-execution.jar:/opt/buildAgent/tools/jps/lib/common.jar:/opt/buildAgent/tools/jps/lib/maven-aether-provider-3.3.9-all.jar:/opt/buildAgent/tools/jps/lib/bundlor-all.jar:/opt/buildAgent/tools/jps/lib/jps-builders-6.jar:/opt/buildAgent/tools/jps/lib/sdk-common.jar:/opt/buildAgent/tools/jps/lib/maven-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/dmServer-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/grails-compiler-patch.jar:/opt/buildAgent/tools/jps/lib/grails-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/devkit-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/org.osgi.namespace.implementation-1.0.0.jar:/opt/buildAgent/tools/jps/lib/plexus-utils-3.0.10.jar:/opt/buildAgent/tools/jps/lib/httpcore-4.4.5.jar:/opt/buildAgent/tools/jps/lib/commons-codec-1.9.jar:/opt/buildAgent/tools/jps/lib/oromatcher.jar:/opt/buildAgent/tools/jps/lib/cli-parser-1.1.jar:/opt/buildAgent/tools/jps/lib/jps-execution-java.jar:/opt/buildAgent/tools/jps/lib/bnd-repository-3.3.0.jar:/opt/buildAgent/tools/jps/lib/jps-builders.jar:/opt/buildAgent/tools/jps/lib/util.jar:/opt/buildAgent/tools/jps/lib/httpmime-4.5.2.jar:/opt/buildAgent/tools/jps/lib/webSphere-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/httpclient-4.5.2.jar:/opt/buildAgent/tools/jps/lib/fluent-hc-4.5.2.jar:/opt/buildAgent/tools/jps/lib/groovy_rt.jar:/opt/buildAgent/tools/jps/lib/sdklib.jar:/opt/buildAgent/tools/jps/lib/flex-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/org.osgi.namespace.contract-1.0.0.jar:/opt/buildAgent/tools/jps/lib/jgoodies-forms.jar:/opt/buildAgent/tools/jps/lib/jps-model.jar:/opt/buildAgent/tools/jps/lib/jps-launcher.jar:/opt/buildAgent/tools/jps/lib/groovy-rt-constants.jar:/opt/buildAgent/tools/jps/lib/bnd-resolve-3.3.0.jar:/opt/buildAgent/tools/jps/lib/jps-execution-kotlin.jar:/opt/buildAgent/tools/jps/lib/javaee-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/gradle-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/jna-platform.jar:/opt/buildAgent/tools/jps/lib/jarutils.jar:/opt/buildAgent/tools/jps/lib/android-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/log4j.jar:/opt/buildAgent/tools/jps/lib/ant-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/guava-21.0.jar:/opt/buildAgent/tools/jps/lib/jps-build-number.jar:/opt/buildAgent/tools/jps/lib/intellilang-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/optimizedFileManager.jar:/opt/buildAgent/tools/jps/lib/weblogic-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/osmorc-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/repository.jar:/opt/buildAgent/tools/jps/lib/manifest-merger.jar:/opt/buildAgent/tools/jps/lib/protobuf-java-2.5.0.jar:/opt/buildAgent/tools/jps/lib/aether-dependency-resolver.jar:/opt/buildAgent/tools/jps/lib/commons-logging-1.2.jar:/opt/buildAgent/tools/jps/lib/ui-designer-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/org.osgi.namespace.service-1.0.0.jar:/opt/buildAgent/tools/jps/lib/plexus-utils-2.0.6.jar:/opt/buildAgent/tools/jps/lib/asm-all.jar:/opt/buildAgent/tools/jps/lib/layoutlib-api.jar:/opt/buildAgent/tools/jps/lib/aether-1.1.0-all.jar:/opt/buildAgent/tools/jps/lib/gwt-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/bndlib-3.3.0.jar:/opt/buildAgent/tools/jps/lib/trove4j.jar:/opt/buildAgent/tools/jps/lib/ecj-4.7.2.jar:/opt/buildAgent/tools/jps/lib/google-app-engine-jps-plugin.jar:/opt/buildAgent/tools/jps/lib/gson-2.8.2.jar:/opt/buildAgent/tools/jps/lib/jps-execution-runtime.jar:/opt/buildAgent/tools/jps/lib/scala-plugin/compiler-interface-sources-2.11.jar:/opt/buildAgent/tools/jps/lib/scala-plugin/sbt-interface.jar:/opt/buildAgent/tools/jps/lib/scala-plugin/compiler-shared.jar:/opt/buildAgent/tools/jps/lib/scala-plugin/compiler-jps.jar:/opt/buildAgent/tools/jps/lib/scala-plugin/nailgun.jar:/opt/buildAgent/tools/jps/lib/scala-plugin/repl-interface-sources.jar:/opt/buildAgent/tools/jps/lib/scala-plugin/compiler-interface.jar:/opt/buildAgent/tools/jps/lib/scala-plugin/scala-library.jar:/opt/buildAgent/tools/jps/lib/scala-plugin/incremental-compiler.jar:/opt/buildAgent/tools/jps/lib/scala-plugin/compiler-interface-sources-2.10.jar:/opt/buildAgent/work/b775fede4ed4637f/tools/kotlin/lib/kotlin-stdlib-common.jar:/opt/buildAgent/work/b775fede4ed4637f/tools/kotlin/lib/kotlin-stdlib-jdk8.jar:/opt/buildAgent/work/b775fede4ed4637f/tools/kotlin/lib/kotlin-reflect.jar:/opt/buildAgent/work/b775fede4ed4637f/tools/kotlin/lib/kotlin-stdlib-jdk7.jar:/opt/buildAgent/work/b775fede4ed4637f/tools/kotlin/lib/kotlin-stdlib.jar:/opt/buildAgent/work/b775fede4ed4637f/tools/kotlin/lib/kotlin-script-runtime.jar:/opt/buildAgent/plugins/antPlugin/ant-runtime.jar:/opt/buildAgent/lib/runtime-util.jar:/opt/buildAgent/lib/serviceMessages.jar:/opt/buildAgent/plugins/idea-runner/idea-runner-common.jar:/opt/buildAgent/plugins/idea-runner/idea-runner-runtime.jar:/opt/buildAgent/plugins/idea-runner/idea-runner-runtime-execution.jar:/opt/buildAgent/plugins/antPlugin/ant-runner.jar:/opt/buildAgent/lib/common.jar:/opt/buildAgent/lib/openapi.jar:/opt/buildAgent/plugins/idea-runner/idea-runner-runtime-api.jar:/opt/buildAgent/lib/messages.jar 
-v